#!/bin/bash
set -euo pipefail
mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<-SQL
CREATE USER IF NOT EXISTS '${APP_DB_USER}'@'%' IDENTIFIED BY '${APP_DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER ON ${MYSQL_DATABASE}.* TO '${APP_DB_USER}'@'%';
FLUSH PRIVILEGES;
SQL
