name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.APP_DB_USER }}
      DB_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ vars.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p${{ secrets.MYSQL_ROOT_PASSWORD }}"
          --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OS deps (Chrome + MySQL client)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg default-mysql-client
          wget -qO- https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv psutil pymysql pytest selenium webdriver-manager

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysql -h ${{ env.DB_HOST }} -uroot -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "SELECT 1" && break
            sleep 2
          done

      - name: Load schema
        run: |
          mysql -h ${{ env.DB_HOST }} -uroot -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" < db/schema.sql

      - name: Create least-privileged app user
        run: |
          mysql -h ${{ env.DB_HOST }} -uroot -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" <<'SQL'
          CREATE USER IF NOT EXISTS '${{ vars.APP_DB_USER }}'@'%' IDENTIFIED BY '${{ secrets.APP_DB_PASSWORD }}';
          GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER ON ${{ env.DB_NAME }}.* TO '${{ vars.APP_DB_USER }}'@'%';
          FLUSH PRIVILEGES;
          SQL

      - name: Run ETL on fixture
        run: |
          python etl/etl.py --file tests/fixtures/311_sample.csv --month 2023-01 --chunksize 5000 --batch 1000

      - name: Start Flask app
        run: |
          nohup python -c "from app.main import app; app.run(host='127.0.0.1', port=5000)" &
          sleep 3

      - name: Run tests (headless)
        env:
          APP_URL: http://127.0.0.1:5000
        run: pytest -q
